version: '3.1'

services:
  sql_server:
    container_name: ExamenSQL
    build: 
      context: .
      target: ExamenSQL
    ports:
      - 15000:1433
    volumes:
      - ./file_db/SQLServer/:/var/opt/mssql/data/
    restart: always
